// This migration script is responsible
// for replacing the actionID of actions
// generated by build_000003.js with a
// randomly generated actionID.

let dbName = 'metis'

if (process.env.MONGO_DB) {
  dbName = process.env.MONGO_DB
}

use(dbName)

print('Migrating mission data to updated schema...')

let cursor_missions = db.missions.find({}, { missionID: 1, nodeData: 1 })

while (cursor_missions.hasNext()) {
  let mission = cursor_missions.next()
  let nodeData = mission.nodeData

  for (let nodeDatum of nodeData) {
    if (nodeDatum.actions) {
      let actions = nodeDatum.actions

      for (let action of actions) {
        if (action.actionID === 'migration-generated-action') {
          action.actionID = `${Math.random()
            .toString(36)
            .substring(2, 15)}${Math.random().toString(36).substring(2, 15)}`
        }
      }
    }
  }

  db.missions.updateOne({ missionID: mission.missionID }, { $set: mission })
}

print('Updating schema build number...')

db.infos.updateOne({ infoID: 'default' }, { $set: { schemaBuildNumber: 18 } })
