import { MetisComponent } from '../MetisComponent'
import type { Mission } from './Mission'

/**
 * An object that makes up a part of a mission, including
 * a mission itself. Examples are nodes, actions, effects,
 * and so on.
 * @note Implement this to make a class compatible.
 */
export abstract class MissionComponent<
  T extends TMetisBaseComponents = TMetisBaseComponents,
  Self extends MissionComponent<T, Self> = MissionComponent<T, any>,
> extends MetisComponent {
  /**
   * The mission associated with the component.
   */
  public abstract get mission(): Self extends Mission<any> ? Self : T['mission']

  /**
   * The path to the component within the mission.
   */
  public abstract get path(): [...MissionComponent<any, any>[], Self]

  /**
   * Issues specific to the child class implementation.
   * These will be added to the issues generated by the
   * base `MissionComponent` class.
   */
  protected abstract get additionalIssues(): TMissionComponentIssue[]

  /**
   * The issues associated with the component that
   * need to be resolved by the designer of the mission.
   */
  public get issues(): TMissionComponentIssue[] {
    let result: TMissionComponentIssue[] = []

    // If the component is marked as deleted, add an issue
    // to notify the user.
    if (this.deleted) {
      result.push({
        component: this,
        type: 'general',
        message: `"${this.name}" has been marked as deleted.`,
      })
    }
    // Append any additional issues from the child class.
    result.push(...this.additionalIssues)

    return result
  }

  /**
   * Whether the component has some issue that needs to
   * be resolved by the designer of the mission. Added
   * context for the issue of the component can be found
   * by checking the `issues` field.
   */
  public get hasIssues(): boolean {
    return this.issues.length > 0
  }

  /**
   * @param message The message describing the issue.
   * @returns A new general issue object with the given message and the component as context.
   */
  public createIssue(
    message: string,
    options: TCreateIssueOptions = {},
  ): TMissionComponentIssue {
    let { type = 'general' } = options
    return {
      component: this,
      type,
      message,
    }
  }

  /**
   * Consolidates the issues from all components and issues
   * passed into one array of issues.
   * @param elements The components or issues to consolidate.
   * @returns The resulting issue array.
   */
  public static consolidateIssues(
    ...elements: Array<MissionComponent<any, any> | TMissionComponentIssue>
  ): TMissionComponentIssue[] {
    return elements.flatMap((element) => {
      if (element instanceof MissionComponent) {
        return element.issues
      } else {
        return [element]
      }
    })
  }
}

/* -- TYPES -- */

/**
 * Defines the type for the `path` property
 * of a mission component.
 */
export type TMissionComponentPath<
  T extends TMetisBaseComponents,
  Self extends MissionComponent<T, Self>,
> = [...MissionComponent<any, any>[], Self]

/**
 * Represents an issue with a mission component
 * that needs to be resolved by the designer in
 * order for the mission to function properly.
 */
export interface TMissionComponentIssue {
  /**
   * The component that has the issue.
   */
  component: MissionComponent<any, any>
  /**
   * The type of issue that is present.
   * This affects how the issue is handled.
   */
  type: 'general' | 'outdated'
  /**
   * The message describing the issue.
   */
  message: string
}

/**
 * Options for `createIssue` method.
 */
export interface TCreateIssueOptions {
  /**
   * The type of issue to create.
   * @default 'general'
   */
  type?: TMissionComponentIssue['type']
}
