// ! DO NOT EDIT THIS FILE ! CREATE 'environment.json' INSTEAD ! //

const PORT = 8080

const MONGO_DB = 'metis'
const MONGO_HOST = 'localhost'
const MONGO_PORT = 27017

module.exports = {
  PORT,
  MONGO_DB,
  MONGO_HOST,
  MONGO_PORT,
}
