// ! DO NOT EDIT THIS FILE ! CREATE 'environment.json' INSTEAD ! //

const args = process.argv.slice(2)

const PORT = 8080
const MONGO_DB = 'metis'
const MONGO_HOST = 'localhost'
const MONGO_PORT = 27017
const HTTP_RATE_LIMIT = 25
const WS_RATE_LIMIT = 25
const FILE_STORE_DIR = './files/store'

// If the caller of the script requested to
// expose the defaults as environment variables,
// then do so here. Note, the NodeJS script must
// be run inside an `eval` command to expose the
// environment variables to the shell.
if (args.includes('--expose') || args.includes('-e')) {
  Object.keys(module.exports).forEach((key) => {
    let value = module.exports[key]

    if (typeof value === 'string') {
      value = `'${value}'`
    }

    console.log(`export ${key}=${value}`)
  })
}

module.exports = {
  PORT,
  MONGO_DB,
  MONGO_HOST,
  MONGO_PORT,
  HTTP_RATE_LIMIT,
  WS_RATE_LIMIT,
  FILE_STORE_DIR,
}
