/** @type {import("jest").Config} **/
export default {
  verbose: true,
  silent: true,
  projects: [
    {
      displayName: 'e2e',
      rootDir: '.',
      coverageDirectory: '<rootDir>/tests/coverage',
      roots: ['<rootDir>/tests/projects/e2e/'],
      testEnvironment: 'node',
      maxWorkers: 1,
      setupFilesAfterEnv: ['<rootDir>/tests/initialize.ts'],
      collectCoverageFrom: [
        '<rootDir>/server/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/shared/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/client/src/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/integration/library/**/*.{ts,tsx,js,jsx}',
        '!<rootDir>/tests/**',
        '!**/*.d.ts',
        '!**/node_modules/**',
        '!**/dist/**',
        '!**/build/**',
        '!**/coverage/**',
      ],
      coveragePathIgnorePatterns: [
        '<rootDir>/tests/',
        '/node_modules/',
        '/dist/',
        '/build/',
        '/coverage/',
      ],
      moduleNameMapper: {
        '^@metis/server$': '<rootDir>/server/MetisServer.ts',
        '^@metis/server/(.+)$': '<rootDir>/server/$1',
        '^@metis/(.+)$': '<rootDir>/integration/library/$1',
        '^@shared/(.+)$': '<rootDir>/shared/$1',
        '^@server/(.+)$': '<rootDir>/server/$1',
        '^@client/(.+)$': '<rootDir>/client/src/$1',
        '^@integrations/schema/(.+)$':
          '<rootDir>/integration/library/schema/$1',
        '^metis/server$': '<rootDir>/server/MetisServer.ts',
        '^metis/server/(.+)$': '<rootDir>/server/$1',
        '^metis$': '<rootDir>/shared/index.ts',
        '^metis/(.+)$': '<rootDir>/shared/$1',
        '^tests/(.+)$': '<rootDir>/tests/$1',
      },
      transform: {
        '^.+\\.[tj]sx?$': [
          'ts-jest',
          {
            tsconfig: '<rootDir>/tests/projects/e2e/tsconfig.json',
          },
        ],
      },
    },
    {
      displayName: 'integration:api',
      rootDir: '.',
      coverageDirectory: '<rootDir>/tests/coverage',
      roots: ['<rootDir>/tests/projects/integration/api/rest'],
      testEnvironment: 'node',
      maxWorkers: 1,
      setupFilesAfterEnv: ['<rootDir>/tests/initialize.ts'],
      collectCoverageFrom: [
        '<rootDir>/server/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/shared/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/client/src/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/integration/library/**/*.{ts,tsx,js,jsx}',
        '!<rootDir>/tests/**',
        '!**/*.d.ts',
        '!**/node_modules/**',
        '!**/dist/**',
        '!**/build/**',
        '!**/coverage/**',
      ],
      coveragePathIgnorePatterns: [
        '<rootDir>/tests/',
        '/node_modules/',
        '/dist/',
        '/build/',
        '/coverage/',
      ],
      moduleNameMapper: {
        '^@metis/server$': '<rootDir>/server/MetisServer.ts',
        '^@metis/server/(.+)$': '<rootDir>/server/$1',
        '^@shared/(.+)$': '<rootDir>/shared/$1',
        '^@server/(.+)$': '<rootDir>/server/$1',
        '^@client/(.+)$': '<rootDir>/client/src/$1',
        '^@metis/(.+)$': '<rootDir>/integration/library/$1',
        '^@integrations/schema/(.+)$':
          '<rootDir>/integration/library/schema/$1',
        '^metis/server$': '<rootDir>/server/MetisServer.ts',
        '^metis/server/(.+)$': '<rootDir>/server/$1',
        '^metis$': '<rootDir>/shared/index.ts',
        '^metis/(.+)$': '<rootDir>/shared/$1',
        '^tests/(.+)$': '<rootDir>/tests/$1',
      },
      transform: {
        '^.+\\.[tj]sx?$': [
          'ts-jest',
          {
            tsconfig:
              '<rootDir>/tests/projects/integration/api/rest/tsconfig.json',
          },
        ],
      },
    },
    {
      displayName: 'integration:websocket',
      rootDir: '.',
      coverageDirectory: '<rootDir>/tests/coverage',
      roots: ['<rootDir>/tests/projects/integration/api/websocket'],
      testEnvironment: 'node',
      maxWorkers: 1,
      setupFilesAfterEnv: ['<rootDir>/tests/initialize.ts'],
      collectCoverageFrom: [
        '<rootDir>/server/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/shared/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/client/src/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/integration/library/**/*.{ts,tsx,js,jsx}',
        '!<rootDir>/tests/**',
        '!**/*.d.ts',
        '!**/node_modules/**',
        '!**/dist/**',
        '!**/build/**',
        '!**/coverage/**',
      ],
      coveragePathIgnorePatterns: [
        '<rootDir>/tests/',
        '/node_modules/',
        '/dist/',
        '/build/',
        '/coverage/',
      ],
      moduleNameMapper: {
        '^@metis/server$': '<rootDir>/server/MetisServer.ts',
        '^@metis/server/(.+)$': '<rootDir>/server/$1',
        '^@shared/(.+)$': '<rootDir>/shared/$1',
        '^@server/(.+)$': '<rootDir>/server/$1',
        '^@client/(.+)$': '<rootDir>/client/src/$1',
        '^@metis/(.+)$': '<rootDir>/integration/library/$1',
        '^@integrations/schema/(.+)$':
          '<rootDir>/integration/library/schema/$1',
        '^metis/server$': '<rootDir>/server/MetisServer.ts',
        '^metis/server/(.+)$': '<rootDir>/server/$1',
        '^metis$': '<rootDir>/shared/index.ts',
        '^metis/(.+)$': '<rootDir>/shared/$1',
        '^tests/(.+)$': '<rootDir>/tests/$1',
      },
      transform: {
        '^.+\\.[tj]sx?$': [
          'ts-jest',
          {
            tsconfig:
              '<rootDir>/tests/projects/integration/api/websocket/tsconfig.json',
          },
        ],
      },
    },
    {
      displayName: 'unit',
      rootDir: '.',
      coverageDirectory: '<rootDir>/tests/coverage',
      roots: ['<rootDir>/tests/projects/unit'],
      testEnvironment: 'node',
      maxWorkers: 1,
      collectCoverageFrom: [
        '<rootDir>/server/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/shared/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/client/src/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/integration/library/**/*.{ts,tsx,js,jsx}',
        '!<rootDir>/tests/**',
        '!**/*.d.ts',
        '!**/node_modules/**',
        '!**/dist/**',
        '!**/build/**',
        '!**/coverage/**',
      ],
      coveragePathIgnorePatterns: [
        '<rootDir>/tests/',
        '/node_modules/',
        '/dist/',
        '/build/',
        '/coverage/',
      ],
      moduleNameMapper: {
        '^@metis/server$': '<rootDir>/server/MetisServer.ts',
        '^@metis/server/(.+)$': '<rootDir>/server/$1',
        '^@metis/(.+)$': '<rootDir>/integration/library/$1',
        '^@shared/(.+)$': '<rootDir>/shared/$1',
        '^@server/(.+)$': '<rootDir>/server/$1',
        '^@client/(.+)$': '<rootDir>/client/src/$1',
        '^@integrations/schema/(.+)$':
          '<rootDir>/integration/library/schema/$1',
        '^metis/server$': '<rootDir>/server/MetisServer.ts',
        '^metis/server/(.+)$': '<rootDir>/server/$1',
        '^metis$': '<rootDir>/shared/index.ts',
        '^metis/(.+)$': '<rootDir>/shared/$1',
        '^tests/(.+)$': '<rootDir>/tests/$1',
      },
      transform: {
        '^.+\\.[tj]sx?$': [
          'ts-jest',
          {
            tsconfig: '<rootDir>/tests/projects/unit/tsconfig.json',
          },
        ],
      },
    },
    {
      displayName: 'unit:client',
      rootDir: '.',
      coverageDirectory: '<rootDir>/tests/coverage',
      roots: ['<rootDir>/tests/projects/unit/client/'],
      testEnvironment: 'jsdom',
      maxWorkers: 1,
      setupFilesAfterEnv: ['<rootDir>/tests/setup/client.ts'],
      collectCoverageFrom: [
        '<rootDir>/client/src/**/*.{ts,tsx,js,jsx}',
        '<rootDir>/shared/**/*.{ts,tsx,js,jsx}',
        '!<rootDir>/tests/**',
        '!**/*.d.ts',
        '!**/node_modules/**',
        '!**/dist/**',
        '!**/build/**',
        '!**/coverage/**',
      ],
      coveragePathIgnorePatterns: [
        '<rootDir>/tests/',
        '/node_modules/',
        '/dist/',
        '/build/',
        '/coverage/',
      ],
      moduleNameMapper: {
        '\\.(scss|css)$': '<rootDir>/tests/mocks/StyleMock.ts',
        '^@metis/server$': '<rootDir>/server/MetisServer.ts',
        '^@metis/server/(.+)$': '<rootDir>/server/$1',
        '^@metis/(.+)$': '<rootDir>/integration/library/$1',
        '^@shared/(.+)$': '<rootDir>/shared/$1',
        '^@server/(.+)$': '<rootDir>/server/$1',
        '^@client/(.+)$': '<rootDir>/client/src/$1',
        '^@integrations/schema/(.+)$':
          '<rootDir>/integration/library/schema/$1',
        '^metis/server$': '<rootDir>/server/MetisServer.ts',
        '^metis/server/(.+)$': '<rootDir>/server/$1',
        '^metis$': '<rootDir>/shared/index.ts',
        '^metis/(.+)$': '<rootDir>/shared/$1',
        '^tests/(.+)$': '<rootDir>/tests/$1',
      },
      transform: {
        '^.+\\.[tj]sx?$': [
          'ts-jest',
          {
            tsconfig: '<rootDir>/tests/projects/unit/client/tsconfig.json',
          },
        ],
      },
    },
  ],
}
