import { IActionOutcomeJSON } from 'metis/missions/actions/outcomes'
import { TMissionNodeJSON } from '../missions/nodes'
import { TActionExecutionJSON } from 'metis/missions/actions/executions'

/**
 * Represents the payloads of data sent from the server to the client over a web socket during various events,
 * or generated by the client itself concerning a web socket connection with the server.
 */
export interface IServerDataTypes {
  /**
   * Occurs when the client is successful in its initial connection to the server.
   */
  'connection-success': {
    method: 'connection-success'
  }
  /**
   * Occurs when the connection with the server is closed purposefully.
   */
  'connection-closed': {
    method: 'connection-closed'
  }
  /**
   * Occurs when the client loses connection to the server unexpectedly.
   */
  'connection-loss': {
    method: 'connection-loss'
  }
  /**
   * Occurs when the client fails to connect to the server.
   */
  'connection-failure': {
    method: 'connection-failure'
  }
  /**
   * Occurs when the client successfully reconnects to the server.
   */
  'reconnection-success': {
    method: 'reconnection-success'
  }
  /**
   * Occurs when the client fails to reconnect to the server.
   */
  'reconnection-failure': {
    method: 'reconnection-failure'
  }
  /**
   * Occurs during any change in the connection status of the client.
   */
  'connection-change': {
    method: 'connection-change'
    status: TServerConnectionStatus
  }
  /**
   * Occurs when the server intenionally emits an error to client.
   */
  'error': {
    method: 'error'
    code: number
    message: string
    request?: {
      method: TClientMethod
      requestID: string
    }
  }
  /**
   * Occurs when a node has been opened on the server.
   */
  'node-opened': {
    method: 'node-opened'
    nodeID: string
    revealedChildNodes: Array<TMissionNodeJSON>
    request: IClientDataTypes['request-open-node']
    requesterID: string
  }
  /**
   * Occurs when the execution of an action is initiated on the server.
   */
  'action-execution-initiated': {
    method: 'action-execution-initiated'
    execution: NonNullable<TActionExecutionJSON>
    request: IClientDataTypes['request-execute-action']
  }
  /**
   * Occurs when the execution of an action has finished on the server.
   */
  'action-execution-completed': {
    method: 'action-execution-completed'
    outcome: IActionOutcomeJSON
    revealedChildNodes?: Array<TMissionNodeJSON>
    request: IClientDataTypes['request-execute-action']
    requesterID: string
  }
}

/**
 * Represents a type of event that occurs on the server that is sent to the client over a web socket.
 */
export type TServerMethod = keyof IServerDataTypes

export type TServerData<TMethod extends TServerMethod> =
  IServerDataTypes[TMethod]

/**
 * Represents the status of a server connection.
 */
export type TServerConnectionStatus = 'open' | 'closed' | 'connecting'

/**
 * Represents the types of data sent from the client to the server over a web socket during various events.
 */
export interface IClientDataTypes {
  'close': {
    method: 'close'
  }
  'error': {
    method: 'error'
    code: number
    message: string
  }
  'request-open-node': {
    method: 'request-open-node'
    requestID: string
    nodeID: string
  }
  'request-execute-action': {
    method: 'request-execute-action'
    requestID: string
    actionID: string
  }
}

/**
 * Represents the type of event that occurs on the client that is sent to the server over a web socket.
 */
export type TClientMethod = keyof IClientDataTypes

export type TClientData<TMethod extends TClientMethod> =
  IClientDataTypes[TMethod]
